pipeline{
    agent any

    environment {
        DOCKERHUB_CREDS = credentials("dockerhub")
        IMAGE_NAME = 'firthunands90/montinorearrecursoslinux'
        GIT_REPO = 'https://github.com/fernandogonzalez90/MonitorearRecursosLinux.git'
        GIT_BRANCH = 'main'
    }

    stages{
        stage('Clonar Repositorio'){
            steps{
                git branch: 'main', url: 'https://github.com/fernandogonzalez90/MonitorearRecursosLinux.git'
            }
        }

        stage('Build Docker Image'){
            steps{
                script {
                    writeFile file: 'Dockerfile', text:'''
                    FROM python:3.10-alpine
                    RUN mkdir /app
                    WORKDIR /app
                    COPY ../App .
                    RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev
                    RUN pip install --upgrade pip
                    RUN pip install -r requirements.txt
                    CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
                    '''
                    sh "docker build -t ${env.IMAGE_NAME}:${BUILD_NUMBER} ."
                    sh "docker run -d -p 8000:8000 ${env.IMAGE_NAME}:${BUILD_NUMBER}"
                }
            }
        }
        
        stage('Push Docker Image'){
            steps{
                    sh 'echo ${DOCKERHUB_CREDS_PSW} | docker login -u ${DOCKERHUB_CREDS_USR} --password-stdin'
                    sh 'docker push ${IMAGE_NAME}:${BUILD_NUMBER}'
                }
            }
        }

        post{
            always {
                echo "Limpiando"
                sh "docker system prune -f"
            }
            success {
                echo "Success !"
            }

            failure {
                echo "Fail !"
            }
        }

    }

    

