pipeline{
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = credentials("docker")
        IMAGE_NAME = 'firthunands90/montinorearrecursoslinux'
        GIT_REPO = 'https://github.com/fernandogonzalez90/MonitorearRecursosLinux.git'
        GIT_BRANCH = 'main'
    }

    stages{
        stage('Clonar Repositorio'){
            steps{
                git branch: "${env.GIT_BRANCH}", url:"${env.GIT_REPO}"
            }
        }

        stage('Build Docker Image'){
            steps{
                script {
                    writeFile file: 'Dockerfile', text:'''
                    FROM python:alpine  
                    WORKDIR /app
                    COPY . /app
                    RUN pip install --no-cache-dir -r requirements.txt
                    '''

                    sh "docker build -t ${env.IMAGE_NAME}:${BUILD_NUMBER} ."
                }
            }
        }
        
        stage('Push Docker Image'){
            steps{
                script{
                    docker.withRegistry('https://registry.hub.docker.com', env.DOCKER_CREDENTIALS_ID){
                        sh "docker push ${env.IMAGE_NAME}:${BUILD_NUMBER}"
                    }
                }
            }
        }
    }
}

post{
    always {
        echo "Limpiando"
        sh "docker system prune -f"
    }
    success {
        echo "Success !"
    }

    failure {
        echo "Fail !"
    }
}