pipeline{
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = credentials("dockerhub")
        IMAGE_NAME = 'firthunands90/calcudolar'
        GIT_REPO = 'https://github.com/fernandogonzalez90/Calcudolar.git'
        GIT_BRANCH = 'master'
    }

    stages{
        stage('Clonar Repositorio'){
            steps{
                git branch: "${env.GIT_BRANCH}", url:"${env.GIT_REPO}"
            }
        }
        
        stage('Instalar Dependencias'){
            steps{
                sh 'npm install'
            }
        }

        stage('Build'){
            steps{
                sh 'npm run build'
            }
        }

        stage('Build Docker Image'){
            steps{
                script {
                    writeFile file: 'Dockerfile', text:'''
                    FROM nginx:alpine
                    COPY build /usr/share/nginx/html
                    '''

                    sh "docker build -t ${env.IMAGE_NAME}:${BUILD_NUMBER}"
                }
            }
        }
        
        stage('Push Docker Image'){
            steps{
                script{
                    docker.withRegistry('https://registry.hub.docker.com', env.DOCKER_CREDENTIALS_ID){
                        sh "docker push ${env.IMAGE_NAME}:${BUILD_NUMBER}"
                    }
                }
            }
        }
    }
}

post{
    always {
        echo "Limpiando"
        sh "docker system prune -f"
    }
    success {
        echo "Success !"
    }

    failure {
        echo "Fail !"
    }
}