FROM python:3.10-alpine
RUN mkdir /app
WORKDIR /app
COPY . .
RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]